verification_task:
  description: >
    Verify the correctness of causal inference tasks and results.
    Ensure that all components are logically sound and consistent with causal principles.
  expected_output: >
    A verification report detailing the integrity of data, DAGs, SCMs, and results.
  agent: verification_agent